name: easygpt
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  assorted_layout_widgets: ^8.0.0
  cupertino_icons: ^1.0.2
  figma_squircle: ^0.5.3
  flutter:
    sdk: flutter
  flutter_highlighter: ^0.1.1
  flutter_markdown: ^0.6.14
  flutter_svg: ^2.0.5
  get: ^4.6.5
  get_storage: ^2.1.1
  http: ^0.13.5
  iconly: ^1.0.1
  ionicons: ^0.2.2
  readmore: ^2.2.0
  rxdart: ^0.27.7
  shimmer: ^2.0.0
  url_launcher: ^6.1.10

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: Estedad
      fonts:
        - asset: assets/fonts/Estedad/Estedad-Thin.ttf
          weight: 100
        - asset: assets/fonts/Estedad/Estedad-Light.ttf
          weight: 200
        - asset: assets/fonts/Estedad/Estedad-ExtraLight.ttf
          weight: 300
        - asset: assets/fonts/Estedad/Estedad-Regular.ttf
          weight: 400
        - asset: assets/fonts/Estedad/Estedad-Medium.ttf
          weight: 500
        - asset: assets/fonts/Estedad/Estedad-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Estedad/Estedad-Bold.ttf
          weight: 700
        - asset: assets/fonts/Estedad/Estedad-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Estedad/Estedad-Black.ttf
          weight: 900

    - family: Urbanist
      fonts:
        - asset: assets/fonts/Urbanist/Urbanist-Thin.ttf
          weight: 100
        - asset: assets/fonts/Urbanist/Urbanist-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Urbanist/Urbanist-Light.ttf
          weight: 300
        - asset: assets/fonts/Urbanist/Urbanist-Regular.ttf
          weight: 400
        - asset: assets/fonts/Urbanist/Urbanist-Medium.ttf
          weight: 500
        - asset: assets/fonts/Urbanist/Urbanist-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Urbanist/Urbanist-Bold.ttf
          weight: 700
        - asset: assets/fonts/Urbanist/Urbanist-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Urbanist/Urbanist-Black.ttf
          weight: 900

  assets:
    # - lib/.env
    - assets/fonts/
    - assets/svg/
    - assets/images/
