name: easygpt
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_highlighter: ^0.1.1
  flutter_markdown: ^0.6.14
  flutter_svg: ^2.0.5
  get: ^4.6.5
  get_storage: ^2.1.1
  http: ^0.13.5
  iconly: ^1.0.1
  ionicons: ^0.2.2
  readmore: ^2.2.0
  shimmer: ^2.0.0
  url_launcher: ^6.1.10
  webview_flutter: ^4.2.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
